server:
  port: 8080
  servlet:
    context-path: /bookpublisher

spring:
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %X{traceId} - [%level] - %msg%n"